services:
  frontend:
    build: ./chatv2
    ports:
      - "4200:4200"
    develop:
      watch:
        - action: sync
          path: ./chatv2
          target: /app
          ignore: 
            - node_modules/
        - action: rebuild
          path: ./chatv2/package.json

  backend:
    build: ./back/backend
    ports:
      - "3000:3000"
    develop:
      watch:
        - action: rebuild
          path: ./back/backend
          target: /app
          ignore: 
            - node_modules/
        - action: rebuild
          path: ./back/backend/package.json
    environment:
      - MONGO_URL=mongodb://db:27017/FLOWCOM
    depends_on:
      - db

  db:
    image: mongo:7.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
