name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-front:
    name: ğŸ¨ Test Frontend (chatv2)
    runs-on: ubuntu-latest

    steps:
    - name: ğŸ“¥ Checkout code
      uses: actions/checkout@v4

    - name: â” Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: ğŸ“¦ Install dependencies Frontend
      run: |
        cd chatv2
        npm install

    - name: ğŸ—ï¸ Build Frontend
      run: |
        cd chatv2
        npm run build

    - name: ğŸ“Š Save Frontend build
      uses: actions/upload-artifact@v4
      with:
        name: frontend-build
        path: chatv2/dist/

  test-back:
    name: ğŸ–¥ï¸ Test Backend (back/backend)
    runs-on: ubuntu-latest
    
    steps:
    - name: ğŸ“¥ Checkout code
      uses: actions/checkout@v4

    - name: â” Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: ğŸ“¦ Install dependencies Backend
      run: |
        cd back/backend
        npm install

    - name: ğŸ—ï¸ Build Backend
      run: |
        cd back/backend
        npm run build

    - name: ğŸ“Š Save Backend build
      uses: actions/upload-artifact@v4
      with:
        name: backend-build
        path: back/backend/dist/